[package]
name = "fastmap"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Specialized version of `HashMap` with H256 keys and fast hashing function."
license = "GPL-3.0"

[dependencies]
plain_hasher = "0.2"

[dependencies.common-libs]
path = "../../common-libs"
features = [
    "ethereum-types"
]